services:
  - type: web
    name: name-analysis-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn name_analysis_api:app
    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}

